[project]
name = "lab3"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "winrt-runtime>=3.2.1",
    "winrt-windows-devices-bluetooth>=3.2.1",
    "winrt-windows-devices-bluetooth-genericattributeprofile>=3.2.1",
    "winrt-windows-foundation>=3.2.1",
    "winrt-windows-foundation-collections>=3.2.1",
    "winrt-windows-storage-streams>=3.2.1",
]
